const recipes = [
    {
        meal: 'Crispy Chili Turkey Noodles',
        ingredients: [
            {ingredient: 'Sesame oil', measure: 2, unit: 'tbsp', category: 'sauces & oils'},
            {ingredient: 'Turkey mince', measure: 500, unit: 'g', category: 'meat & poultry'},
            {ingredient: 'Fresh ginger', measure: 5, unit: 'cm', category: 'spices'},
            {ingredient: 'Garlic', measure: 1, unit: 'clove', category: 'spices'},
            {ingredient: 'Honey', measure: 3, unit: 'tbsp', category: 'carbohydrates'},
            {ingredient: 'Hot sriracha chili sauce', measure: 1, unit: 'tbsp', category: 'sauces & oils'},
            {ingredient: 'Dried onion noodles', measure: 350, unit: 'g', category: 'pasta & rice'},
            {ingredient: 'Lime', measure: 2, unit: 'limes', category: 'fruits'},
            {ingredient: 'Large carrot', measure: 2, unit: 'carrots', category: 'vegitables'},
            {ingredient: 'Spring onion', measure: 4, unit: 'spring onions', category: 'vegitables'},
            {ingredient: 'Corriander', measure: 1, unit: 'small bunch', category: 'herbs'}
        ],
        servings: 2,
        kcal: 566,
        fat: 8,
        saturates: 1,
        carbs: 83,
        sugars: 19,
        fibre: 2,
        protein: 40,
        description: 'Crisp-fried turkey mince in a chilli, soy and garlic sauce atop udon noodles makes for a savoury 20-minute meal that\'s low in fat but big on flavour',
        source: 'https://www.bbcgoodfood.com/recipes/crispy-chilli-turkey-noodles',
        favorite: false,
        selected: false,
        current: false
    },
    {
        meal: 'Stir-fried Chicken with Broccoli and Brown Rice',
        ingredients: [
            {ingredient: 'Brocolli', measure: 200, unit: 'g', category: 'vegitables'},
            {ingredient: 'Chicken breast', measure: 1, unit: 'breast', category: 'meat & poultry'},
            {ingredient: 'Fresh ginger', measure: 15, unit: 'g', category: 'spices'},
            {ingredient: 'Garlic', measure: 1, unit: 'clove', category: 'spices'},
            {ingredient: 'Red onion', measure: 1, unit: 'onion', category: 'vegitables'},
            {ingredient: 'Red pepper', measure: 1, unit: 'pepper', category: 'vegitables'},
            {ingredient: 'Olive oil', measure: 2, unit: 'tbsp', category: 'sauces & oils'},
            {ingredient: 'Chili powder', measure: 1, unit: 'tsp', category: 'spices'},
            {ingredient: 'Reduced-salt soy sauce', measure: 1, unit: 'tbsp', category: 'sauces & oils'},
            {ingredient: 'Honey', measure: 1, unit: 'tbsp', category: 'carbohydrates'},
            {ingredient: 'Brown rice (cooked)', measure: 250, unit: 'g', category: 'pasta & rice'}
        ],
        servings: 2,
        kcal: 488,
        fat: 9,
        saturates: 2,
        carbs: 56,
        sugars: 15,
        fibre: 2,
        protein: 33,
        description: '',
        source: '',
        favorite: false,
        selected: false,
        current: false
    },
    {
        meal: 'Low fat Turkey Bolognese',
        ingredients: [
            {ingredient: 'Turkey mince', measure: 400, unit: 'g', category: 'meat & poultry'},
            {ingredient: 'Vegitable oil', measure: 2, unit: 'tbsp', category: 'sauces & oils'},
            {ingredient: 'Large onion', measure: 1, unit: 'onion', category: 'vegitables'},
            {ingredient: 'Large carrot', measure: 1, unit: 'carrot', category: 'vegitables'},
            {ingredient: 'Celery', measure: 3, unit: 'sticks', category: 'vegitables'},
            {ingredient: 'Sugar', measure: 1, unit: 'pinch', category: 'carbohydrates'},
            {ingredient: 'Tomato puree', measure: 1, unit: 'tbsp', category: 'sauces & oils'},
            {ingredient: 'Chopped tomatos', measure: 2, unit: 'cans (400ml)', category: 'canned vegitables'},
            {ingredient: 'Chicken stock (low-sodium cube)', measure: 400, unit: 'ml', category: 'broths & stocks'},
            {ingredient: 'Wholemeal pasta', measure: 0, unit: 'packet instructions', category: 'pasta & rice'},
            {ingredient: 'Fresh basil', measure: 0, unit: 'garnish', category: 'herbs'}
        ],
        servings: 5,
        kcal: 267,
        fat: 13,
        saturates: 3,
        carbs: 15,
        sugars: 12,
        fibre: 6,
        protein: 23,
        description: '',
        favorite: false,
        selected: false,
        current: false
    }
    /* {
        meal: '',
        ingredients: [
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''}
        ],
        servings: ,
        kcal: ,
        fat: ,
        saturates: ,
        carbs: ,
        sugars: ,
        fibre: ,
        protein: ,
        description: '',
        source: '',
        favorite: false,
        selected: false,
        current: false
    }*/
    /* {
        meal: '',
        ingredients: [
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''},
            {ingredient: '', measure: , unit: '', category: ''}
        ],
        servings: ,
        kcal: ,
        fat: ,
        saturates: ,
        carbs: ,
        sugars: ,
        fibre: ,
        protein: ,
        description: '',
        source: '',
        favorite: false,
        selected: false,
        current: false
    }*/
]